### ISSUE TITLE
Typo in console command

### ISSUE THREAD

**Issue by JPMarquardt** [tkella47/BioChem_DiffDock#3]
For those using Mac (not sure if this is a problem on PC)

The current console command 

`python process_ligand_protein path_to_dir/file.pbd --output_path path_to_dir/diffdocked.pdb`

to generates the error:

`python: can't open file 'path_to_dir/process_ligand_protein': [Errno 2] No such file or directory`

Edit it to say

`python process_ligand_protein.py path_to_dir/file.pbd --output_path path_to_dir/diffdocked.pdb`

and it works

**Comment by tkella47** [comment]
Fixed
