### ISSUE TITLE
Processing PDB File step

### ISSUE THREAD

**Issue by lasyad** [tkella47/BioChem_DiffDock#4]
Hi! In the processing PDB File step, it says to run "python process_ligand_protein.py PATH_TO_YOUR_SAVE_FILE.pdb" 

Where do I run this though? If I do it in python, it says syntax error, and also am I supposed to substitute in the address of where the python program and pdb file in the path_to_your_save_file. I'm on a PC, if that changes anything!

**Comment by tkella47** [comment]
Please copy and paste that command directly into the anaconda prompt. 

If you are getting a syntax error, you are running these commands in the python interpreter, which is not desired behavior.

In PATH_TO_YOUR_FILE.pdb, this is the location to your .pdb file. 
For example if you download the file to downloads on PC, the location C:\Users\Downloads\your.pdb 

Does this solve the issues?
