### ISSUE TITLE
Ligplot+ blank after opening pdb files

### ISSUE THREAD

**Issue by EeshaG2** [tkella47/BioChem_DiffDock#7]
When I open the diffdocked.pdb or 2hyy.pdb on Ligplot+ nothing shows up. Am I supposed to change some parameters?

**Comment by tkella47** [comment]
Can you please attach the the diffdock.pdb file here?

**Comment by EeshaG2** [comment]
Can't attach .pdb file; emailed!

**Comment by tkella47** [comment]
[diffdocked.txt](https://github.com/tkella47/BioChem_DiffDock/files/13405403/diffdocked.txt)

**Comment by EeshaG2** [comment]
There is an error displayed on terminal: "java.io.IOException: Cannot run program "/Users/LigPlus/lib/exe_mac64/hbadd": error=86, Bad CPU type in executable"

**Comment by tkella47** [comment]
This is caused by the Mac CPU using ARM instead of x86. 
Please open a terminal and run 
`softwareupdate --install-rosetta`

**Comment by tkella47** [comment]
Please follow additional instructions here 
[https://support.apple.com/en-us/HT211861](https://support.apple.com/en-us/HT211861)

**Comment by EeshaG2** [comment]
I got a bunch of security errors that I had to manually ignore in settings after I installed rosetta and tried to open the file again, but it works now! Thanks!

**Comment by tkella47** [comment]
Glad this was resolved. LigPlot was developed a while ago, so I don't think the code was written with non-intel CPU's in mind. 
Thank you for bringing up this issue though, it is helpful.
